version: '3.9'

services:
  db:
    image: postgres:alpine
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 6543:5432
    networks:
      - app-network

networks:
  app-network:
    driver: bridge